services:
#  nginx:
#    image: nginx:1.24
#    volumes:
#      - ./etc/nginx/conf.d:/etc/nginx/conf.d
#      - ./public:/public
#    ports:
#      - "80:80"
#    links:
#      - app

  app:
    # Go実装の場合は golang/ PHP実装の場合は php/
    build: golang/
    container_name: app
    environment:
      ISUCONP_DB_HOST: mysql
      ISUCONP_DB_PORT: 3306
      ISUCONP_DB_USER: root
      ISUCONP_DB_PASSWORD: root
      ISUCONP_DB_NAME: isuconp
      ISUCONP_MEMCACHED_ADDRESS: memcached:11211
    links:
      - mysql
      - memcached
    volumes:
      - ./public:/home/public
    init: true
    ports:
      - 8080:8080
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1g

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      #- "TZ=Asia/Tokyo"
      - "MYSQL_ROOT_HOST=%"
      - "MYSQL_ROOT_PASSWORD=root"
    volumes:
      - mysql:/var/lib/mysql
      - ./etc/my.cnf:/etc/my.cnf
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1g

  memcached:
    container_name: memcached
    image: memcached:1.6

volumes:
  mysql:
